name: CI/CD SpeakShot

on:
  push:
    branches: [master]
    paths:
      - "Dockerfile"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"
      - "**/*.json"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          IMAGE="ghcr.io/everjr18/speakshot:latest"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy via SSH (Swarm service update)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euo pipefail
            IMAGE="ghcr.io/everjr18/speakshot:latest"
            SERVICE="speakshot_web"
            docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" -p "${{ secrets.GHCR_TOKEN }}"
            docker service update \
              --with-registry-auth \
              --image "$IMAGE" \
              --force "$SERVICE"
